### ISSUE TITLE
How to tell docker swarm to use seaweedfs?

### ISSUE THREAD

**Issue by bearylabs** [cycneuramus/seaweedfs-docker-swarm#1]
Hey,

I recently installed SeaweedFS on my Docker swarm according to the instructions in the repository. I made sure to update the hostnames and network name as required, and everything seems to be working fine. However, I'm new to this topic and I'm not sure how to use SeaweedFS or how to configure Docker to use persistent storage. Can you help me with this? I apologize if this is a basic question, but any guidance would be greatly appreciated.

Thanks in Advance

Hendrik

**Comment by cycneuramus** [comment]
I don't think this is the place to ask for general IT support, but if you're alright with getting some general answers, I think a good place to start is to look through the relevant documentation, e.g. the [SeaweedFS wiki](https://github.com/seaweedfs/seaweedfs/wiki) and Docker's [section on volumes](https://docs.docker.com/compose/compose-file/compose-file-v3/#volumes).

If I've understood your issue correctly, though, you don't need any additional Docker magic to use SeaweedFS as persistent storage; the [mount](https://github.com/cycneuramus/seaweedfs-docker-swarm/blob/master/docker-compose.yml#L60-L79) service should make sure that your SeaweedFS storage is mounted at `/mnt/cld` on every Swarm node (hence the "global" deploy mode at line 79).

**Comment by bearylabs** [comment]
I apologize for posting my question here; I didn't know where else to ask. I assumed that once the containers were running, it would function like my NFS drive. However, I now realize that I don't have enough understanding of the subject matter to get Seaweed running without a specific tutorial.

Nevertheless, thank you very much.

**Comment by cycneuramus** [comment]
No worries. SeaweedFS is pretty difficult to get the hang of. I hope you'll be able to sort it out.
